// Generated by scripts/icon/generate-icon.mts (`npm run icon`); do not edit.
/** The Dunder icon the installer puts in the desktop's icon theme. */
export const ICON_SVG =
	'<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512" role="img" aria-label="Dunder">\n<title>Dunder</title>\n<rect x="24" y="24" width="464" height="464" rx="104" fill="#c4bcac"/>\n<rect x="34" y="34" width="444" height="444" rx="94" fill="#f4f1ea"/>\n<path fill="#1f2328" fill-rule="evenodd" d="M142 116H242A128 140 0 0 1 242 396H142ZM204 178H242A66 78 0 0 1 242 334H204Z"/>\n</svg>\n';
