import { type Layout, layoutSchema } from "./schema";

/**
 * The starter office, modelled on docs/reference/orpex-office.png: a long
 * right wall with the company sign, windows on the left wall, a sales and a
 * delivery floor bound to herdr workspaces, and the usual company corners.
 * Room spans x ∈ [-13, 13], z ∈ [-10, 10]; the back corner is (-13, -10).
 */
export const DEFAULT_LAYOUT: Layout = layoutSchema.parse({
	version: 1,
	room: {
		width: 26,
		depth: 20,
		wallHeight: 4.2,
		floorColor: "#cfa979",
		wallColor: "#f1e5cc",
		windows: [
			{ wall: "left", offset: 3.2, width: 3.2, height: 1.1, sill: 2.4 },
			{ wall: "left", offset: 8.2, width: 3.2, height: 1.1, sill: 2.4 },
			{ wall: "left", offset: 13.2, width: 3.2, height: 1.1, sill: 2.4 },
			{ wall: "left", offset: 17.6, width: 2.6, height: 1.1, sill: 2.4 },
			{ wall: "right", offset: 21.5, width: 3.4, height: 1.8, sill: 1.4 },
		],
		sign: { title: "HERDR OFFICE", subtitle: "AI-NATIVE COMPANY · RUNS ON HERDR", offset: 13.2 },
	},
	zones: [
		{
			id: "sales",
			title: "#SALES",
			subtitle: "growth · client love",
			workspaceLabel: "sales",
			rug: { center: { x: -6.6, z: 3.4 }, width: 7.6, depth: 7.4, color: "#b9a58a" },
			labelAt: { x: -8.6, z: 6.6 },
		},
		{
			id: "delivery",
			title: "#DELIVERY",
			subtitle: "watch them coordinate — live",
			workspaceLabel: "delivery",
			rug: { center: { x: 2.6, z: -4.4 }, width: 9.6, depth: 6.6, color: "#a9b48f" },
			labelAt: { x: 0.2, z: -7.2 },
		},
		{
			id: "you",
			title: "YOUR DESK",
			subtitle: "what needs you lands here",
			rug: { center: { x: 7.6, z: 2.4 }, width: 5.4, depth: 4.8, color: "#9fb69a" },
			labelAt: { x: 7.6, z: 1.2 },
			labelHeight: 2.6,
		},
		{
			id: "break-room",
			title: "BREAK ROOM",
			subtitle: "the bell rings here",
			rug: { center: { x: -10.2, z: 6.4 }, width: 5, depth: 5.6, color: "#c9a7a0" },
			labelAt: { x: -10.6, z: 4.2 },
		},
		{
			id: "clients",
			title: "CLIENTS — OPEN THE CRM",
			subtitle: "a panel, not a desk",
			labelAt: { x: -10.6, z: -3.2 },
		},
		{
			id: "mailroom",
			title: "MAILROOM",
			subtitle: "agent mail",
			labelAt: { x: -4.4, z: -8.6 },
			labelHeight: 2.8,
		},
		{
			id: "library",
			title: "LIBRARY — COMPANY BRAIN",
			subtitle: "shared memories",
			labelAt: { x: 5.6, z: -8.4 },
			labelHeight: 2.9,
		},
		{
			id: "reception",
			title: "RECEPTION — HIRING",
			subtitle: "hire an agent",
			labelAt: { x: 5.4, z: 7.8 },
		},
	],
	desks: [
		{
			id: "sales-1",
			position: { x: -8.3, z: 1.6 },
			rotation: 0,
			zoneId: "sales",
			chairColor: "#2f5d63",
		},
		{
			id: "sales-2",
			position: { x: -5.4, z: 1.6 },
			rotation: 0,
			zoneId: "sales",
			chairColor: "#5d3f6a",
		},
		{
			id: "sales-3",
			position: { x: -8.3, z: 4.9 },
			rotation: 0,
			zoneId: "sales",
			chairColor: "#2f5d63",
		},
		{
			id: "sales-4",
			position: { x: -5.4, z: 4.9 },
			rotation: 0,
			zoneId: "sales",
			chairColor: "#5d3f6a",
		},
		{
			id: "delivery-1",
			position: { x: -0.6, z: -5.6 },
			rotation: 0,
			zoneId: "delivery",
			chairColor: "#3d4a5c",
		},
		{
			id: "delivery-2",
			position: { x: 2.4, z: -5.6 },
			rotation: 0,
			zoneId: "delivery",
			chairColor: "#3d4a5c",
		},
		{
			id: "delivery-3",
			position: { x: 5.4, z: -5.6 },
			rotation: 0,
			zoneId: "delivery",
			chairColor: "#3d4a5c",
		},
		{
			id: "delivery-4",
			position: { x: -0.6, z: -2.4 },
			rotation: 0,
			zoneId: "delivery",
			chairColor: "#2f6b4c",
		},
		{
			id: "delivery-5",
			position: { x: 2.4, z: -2.4 },
			rotation: 0,
			zoneId: "delivery",
			chairColor: "#2f6b4c",
		},
		{
			id: "delivery-6",
			position: { x: 5.4, z: -2.4 },
			rotation: 0,
			zoneId: "delivery",
			chairColor: "#2f6b4c",
		},
		{ id: "open-1", position: { x: 1.2, z: 3.4 }, rotation: 90, chairColor: "#6b4f3a" },
		{ id: "open-2", position: { x: 1.2, z: 6.2 }, rotation: 90, chairColor: "#6b4f3a" },
		{
			id: "your-desk",
			position: { x: 7.6, z: 2.6 },
			rotation: 0,
			zoneId: "you",
			reserved: true,
			chairColor: "#24272c",
		},
	],
	decor: [
		{ id: "sofa", kind: "sofa", position: { x: -12.2, z: 6.4 }, rotation: 90 },
		{ id: "break-table", kind: "coffee-table", position: { x: -10.4, z: 6.4 } },
		{ id: "break-armchair", kind: "armchair", position: { x: -9.6, z: 8.6 }, rotation: 200 },
		{ id: "break-lamp", kind: "floor-lamp", position: { x: -12.3, z: 8.8 } },
		{ id: "water-cooler", kind: "water-cooler", position: { x: -12.4, z: 3.6 }, rotation: 90 },
		{ id: "crm-armchair-1", kind: "armchair", position: { x: -11.8, z: -1.6 }, rotation: 90 },
		{ id: "crm-armchair-2", kind: "armchair", position: { x: -11.8, z: -4.2 }, rotation: 90 },
		{ id: "crm-table", kind: "coffee-table", position: { x: -10.2, z: -2.9 } },
		{ id: "mail-cubby", kind: "mail-cubby", position: { x: -4.4, z: -9.6 } },
		{ id: "printer", kind: "printer", position: { x: -2.4, z: -9.5 } },
		{ id: "shelf-1", kind: "bookshelf", position: { x: 3.6, z: -9.7 } },
		{ id: "shelf-2", kind: "bookshelf", position: { x: 5.8, z: -9.7 } },
		{ id: "shelf-3", kind: "bookshelf", position: { x: 8, z: -9.7 } },
		{ id: "server-rack", kind: "server-rack", position: { x: 11.6, z: -5.4 }, rotation: -90 },
		{ id: "reception", kind: "reception-desk", position: { x: 5.4, z: 7.4 } },
		{ id: "open-roles", kind: "notice-board", position: { x: 8.6, z: 8.2 }, rotation: -20 },
		{
			id: "bell",
			kind: "wall-bell",
			position: { x: -13, z: -7.6 },
			rotation: 90,
			elevation: 2.9,
			label: "AGENT BELL",
		},
		{ id: "tv", kind: "wall-tv", position: { x: -6.6, z: -10 }, elevation: 2.9 },
		{ id: "clock", kind: "wall-clock", position: { x: 9.6, z: -10 }, elevation: 3 },
		{ id: "plant-1", kind: "plant", position: { x: -11.8, z: 0.8 } },
		{ id: "plant-2", kind: "plant", position: { x: -10.6, z: 9.2 } },
		{ id: "plant-3", kind: "plant", position: { x: -2.8, z: 9 } },
		{ id: "plant-4", kind: "plant", position: { x: 10.4, z: 8.6 } },
		{ id: "plant-5", kind: "plant", position: { x: 4.4, z: 5.2 } },
		{ id: "plant-6", kind: "tall-plant", position: { x: -6.2, z: -9.3 } },
		{ id: "plant-7", kind: "tall-plant", position: { x: 12.2, z: -9.2 } },
		{ id: "plant-8", kind: "plant", position: { x: -12.2, z: -8.8 } },
	],
	callouts: [
		{
			id: "access",
			title: "ACCESS",
			subtitle: "herdr · office session",
			position: { x: 11.6, z: -5.4 },
			height: 2.6,
		},
	],
});
